- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages."
  become: true
  apt:
    upgrade: "yes"

- name: "install node 13.X"
  shell: |
    curl -sL https://deb.nodesource.com/setup_13.x | sudo -E bash -
    sudo apt install -y nodejs
- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present      

- name: "install node_exporter"
  shell: |
    wget https://github.com/prometheus/node_exporter/releases/download/v1.0.1/node_exporter-1.0.1.linux-amd64.tar.gz
    tar xzf node_exporter-1.0.1.linux-amd64.tar.gz
    sudo cp node_exporter-1.0.1.linux-amd64/node_exporter /usr/local/bin/node_exporter
    rm -rf node_exporter-1.0.1.linux-amd64.tar.gz node_exporter-1.0.1.linux-amd64