version: 2.1

commands:
  print_pipeline_id:
    steps:
      - run: echo ${CIRCLE_WORKFLOW_ID}

jobs:
  build_frontend:
    docker:
      - image: circleci/node:13.8.0
    working_directory: ~/ci-cd-webapp/frontend
    steps:
      - checkout:
          path: ~/ci-cd-webapp
      - restore_cache:
          keys:
            - nm-{{ checksum "package.json" }}
            - nm-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: nm-{{ checksum "package.json" }}
      - run: npm run lint
  test_frontend:
    docker:
      - image: circleci/node:13.8.0
    working_directory: ~/ci-cd-webapp/frontend
    steps:
      - checkout:
          path: ~/ci-cd-webapp
      - restore_cache:
          keys:
            - nm-{{ checksum "package.json" }}
            - nm-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: nm-{{ checksum "package.json" }}
      - run: npm run test
  analyze_frontend:
    docker:
      - image: circleci/node:13.8.0
    working_directory: ~/ci-cd-webapp/frontend
    steps:
      - checkout:
          path: ~/ci-cd-webapp
      - restore_cache:
          keys:
            - nm-{{ checksum "package.json" }}
            - nm-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: nm-{{ checksum "package.json" }}
      - run: npm run audit

workflows:
  ci_frontend:
    jobs:
      - build_frontend
      - test_frontend:
          requires:
            - build_frontend
      - analyze_frontend:
          requires:
            - test_frontend
